

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "150m"
    max-file: "3"

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.prometheus.yml
      # - --web.route-prefix=/
      # - --web.external-url=/prometheus/
    networks:
      - monitoring_bridge
    ports:
      - "9990:9090"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/prometheus/web.prometheus.yml:/etc/prometheus/web.prometheus.yml
      - ./metrics/prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
    depends_on:
     - alertmanager
    logging: *default-logging
  
  alertmanager:
    image: prom/alertmanager:v0.27.0
    restart: unless-stopped
    networks:
      - monitoring_bridge
    ports:
      - "9993:9093"
    volumes:
      - ./metrics/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./metrics/alertmanager/web.alertmanager.yml:/etc/alertmanager/web.alertmanager.yml
      - alertmanager-data:/data
    command: 
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --web.config.file=/etc/alertmanager/web.alertmanager.yml
      - --log.level=info

  grafana:
    image: grafana/grafana:10.2.2
    restart: unless-stopped
    networks:
      - monitoring_bridge
    ports:
      - "9999:3000"
    volumes:
      - monitoring_grafana:/var/lib/grafana
      - ./metrics/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./metrics/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
      # - ./cert:/var/lib/grafana/ssl/cert:ro
    environment:
      GF_INSTALL_PLUGINS: yesoreyeram-boomtable-panel,agenty-flowcharting-panel
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_EMAIL: ${GRAFANA_ADMIN_EMAIL}
      GF_SECURITY_ADMIN_DISABLE_GRAVATAR: true
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_AUTH_BASIC_ENABLED: false
      GF_USERS_DEFAULT_THEME: dark
      GF_LOG_CONSOLE_LEVEL: info
      GF_SERVER_ENABLE_GZIP: true
      GF_SERVER_PROTOCOL: http
      # GF_SERVER_CERT_FILE: /var/lib/grafana/ssl/cert/tls.crt
      # GF_SERVER_CERT_KEY: /var/lib/grafana/ssl/cert/tls.key
    logging: *default-logging
    depends_on:
      - prometheus

volumes:
  monitoring_grafana:
  alertmanager-data:

networks:
  monitoring_bridge:
    driver: bridge