groups:
  - name: targetStatus
    rules:
    - alert: targetDown
      expr: up == 0
      for: 30s
      labels:
        severity: page
      annotations:
        summary: "Server down !"
        description: "**{{$labels.instance}}** of job **{{$labels.job}}** has been down for more than *1 minute.*"