global:
  scrape_interval:     15s # Default scrape interval
  evaluation_interval:   15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: 
          - alertmanager:9093
      basic_auth:
        username: elanza48
        password: elanza48_prometheus_alertmanager
      

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: server_monitoring
    scheme: http
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 5s
    static_configs:
    - targets: 
      - host.docker.internal:9191
      labels: 
        service: VM Server
    basic_auth:
      username: elanza48
      password: DEwoMIumeiTYrEdOGRic
