
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "150m"
    max-file: "3"

services:
  nginx:
      image: nginx:1.25.3-alpine
      restart: unless-stopped
      network_mode: host
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./nginx/include:/etc/nginx/include:ro
        - ./nginx/secret:/etc/nginx/secret:ro
        # - ./cert:/etc/nginx/ssl/cert:ro
      logging: *default-logging
      depends_on:
        - prom_node_exporter

  prom_node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.sysctl'
      - '--collector.systemd'
      - '--collector.interrupts'
      - '--collector.logind'
      - '--collector.processes'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    network_mode: host
    pid: host
    restart: unless-stopped
    security_opt:
    - "apparmor:unconfined"
    volumes:
      - /:/rootfs:ro,rslave
      - /run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    logging: *default-logging