route:
  receiver: 'telegram'
  repeat_interval: 3h
  group_wait: 30s
  group_interval: 5m
  group_by: 
    - alertname

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token : TOKEN
    api_url: https://api.telegram.org
    chat_id: 1234
    parse_mode: MarkdownV2

